name: Demo
on:
  push:
      branches: 
        - '**'
  pull_request:
      branches:
         - '**'
  schedule:
    - cron: "*/6 0 * * *"
  workflow_dispatch:

    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN_DEMO }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and run Spectral CI
      uses: spectralops/spectral-github-action@v2
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN_DEMO }}
        spectral-args: scan --ok  --include-tags base,audit3,iac
