name: Demo
on:
  push:
      branches: 
        - '**'
  pull_request:
      branches:
         - '**'
  schedule:
    - cron: "*/6 0 * * *"
  workflow_dispatch:

    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN_DEMO }}

jobs:
  scan:
    name: Spectral-organization-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN_DEMO }}
        run: |
          curl -L "https://get.spectralops.io/latest/x/sh?dsn=${{ secrets.SPECTRAL_DSN_DEMO }}"  | sh
          $HOME/.spectral/spectral scan --ok --include-tags base,audit3,iac
